function [fitresult, gof] = createFits(t, mean_I)
%CREATEFITS(T2,MEAN_I2,T0,MEAN_I0,T,MEAN_I)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t2
%      Y Output: mean_I2
%  Data for 'untitled fit 2' fit:
%      X Input : t0
%      Y Output: mean_I0
%  Data for 'untitled fit 3' fit:
%      X Input : t
%      Y Output: mean_I
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Sep-2018 15:05:50

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 3, 1 );
gof = struct( 'sse', cell( 3, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, mean_I );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [791.978057001671 -0.00265910619426656];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'Datos', 'Ajuste exponencial', 'Location', 'NorthEast' );
% Label axes
xlabel Tiempo
ylabel Intensidad de pixel
grid on



